### ISSUE TITLE
Errors?

### ISSUE THREAD

**Issue by janewhitaker** [anoopsankar/Trakt2Letterboxd#3]
![image](https://user-images.githubusercontent.com/35536407/35055204-eb0cc8b0-fbae-11e7-9b58-89767d3dcb6b.png)

Hi there! I have very limited/no knowledge of coding/python and I'm getting this error. Is there any way to fix this? I'm running it on Mac OS (10.13.2).

**Comment by anoopsankar** [comment]
Do you have python installed? What is the command that you are using to run the script?

**Comment by janewhitaker** [comment]
I do have python installed. I copy pasted the file into the terminal in attempt to get the right directory because when I ran 'python Trakt2Letterboxd.py' it gave me this error: 
<img width="697" alt="screen shot 2018-01-18 at 17 43 21" src="https://user-images.githubusercontent.com/35536407/35109614-28260928-fc77-11e7-9d68-fe318cfb67ea.png">

**Comment by anoopsankar** [comment]
Nope!.. It will not work if you copy paste the file on the terminal.

Follow these steps verbatim on the terminal:

```
git clone https://github.com/anoopsankar/Trakt2Letterboxd.git
cd Trakt2Letterboxd/
python Trakt2Letterboxd.py
```

Then follow instructions on the screen.

**Comment by janewhitaker** [comment]
This worked, thanks!
