### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by willag42** [anoopsankar/Trakt2Letterboxd#5]
Hello, I've been trying to get this code to work for the past hour, and I'm uncertain if I'm just doing it wrong or if the code doesn't work anymore.

I have downloaded both Python 3.9.0 and Python 2.7.15. I initially started with the first, but then saw the note about how the script requires Python2.x to run, so I tried downloading the latter.

I have tried running 'python Trak2Letterboxd.py' in the Windows Command Prompt and nothing happens.

I have tried running it in the Python 3.9 command line and get the following:
`Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python Trakt2Letterboxd.py
  File "<stdin>", line 1
    python Trakt2Letterboxd.py
           ^
SyntaxError: invalid syntax
>>>`

And I have tried it in the Python 2.7.15 command line and get the same error:
`Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python Trak2Letterboxd.py
  File "<stdin>", line 1
    python Trak2Letterboxd.py
                         ^
SyntaxError: invalid syntax
>>>`

Am I missing something?

Thank you.

**Comment by anoopsankar** [comment]
So, you are trying to run the command on the python interactive shell, which is not what we want.

To run the script on Windows - Press the windows key, type `cmd` followed by Enter. You'll see a terminal screen open up. On that please enter `C:\python27\python.exe C:\Trakt2Letterboxd.py` and you should be ready to go.

This assumes that:
1. You have installed python in the default folder (C:\python27). If not installed in default path, please change the path in above command accordingly.
2. The script file is on C:\ folder. If not please copy the file 'Trakt2Letterboxd.py' to C:\ or replace the path with the actual.

NB: I don't have a windows machine ready to verify this entirely; but these steps should work. 

You can have a look [here](https://www.cs.bu.edu/courses/cs108/guides/runpython.html) (under _Run your script_) for some more info.

**Comment by willag42** [comment]
Thank you very much! This seemed to at least get me to the point where I could authenticate on trakt.tv. However, an error occurred and the script wasn't able to complete.

`Initializing...

Go to https://trakt.tv/activate on your web browser and enter the below user code there:

[CODE]

After you have authenticated and given permission;come back here to continue.

Waiting for authorization. . . . . . Authenticated!
Token:28ddbadc350fc66b44c672a035dde7e3697376e32e9ba6969b97521c0139dce9
Getting history
Completed page 1 of 33
Completed page 2 of 33
Completed page 3 of 33
Completed page 4 of 33
Completed page 5 of 33
Completed page 6 of 33
Completed page 7 of 33
Completed page 8 of 33
Completed page 9 of 33
Completed page 10 of 33
Completed page 11 of 33
Completed page 12 of 33
Completed page 13 of 33
Completed page 14 of 33
Completed page 15 of 33
Completed page 16 of 33
Completed page 17 of 33
Completed page 18 of 33
521 An error occured. Please re-run the script`

Re-running the script stops it on page 1 the second time.

**Comment by willag42** [comment]
Never mind the post I just made. I looked online and saw the 521 error code was related to the TCP connection to trakt. I waited a few minutes and tried again and was able to download the file.

Thank you very much for your help!

**Comment by anoopsankar** [comment]
Glad to know that it helped!

I'm closing the issue now since it has been resolved.
