### ISSUE TITLE
Trakt ratings

### ISSUE THREAD

**Issue by forenta** [anoopsankar/Trakt2Letterboxd#7]
With the tool, it was really damn easy to take the history of the scrobbled movies. Thanks a lot for the great work!

Unfortunately, it seems that so far the ratings from Trakt are not taken over (e.g. ',6' at the end of the .csv lines). Would it still be possible to bring these along using the tool as well?

**Comment by hbar137** [comment]
Hi there! I needed to download ratings as well so modified the script. You can find it at https://github.com/hbar137/Trakt2Letterboxd. @anoopsankar, please let me know if you would rather me not post a modified version of your code. Thank you!

**Comment by anoopsankar** [comment]
Well, as long as you have abided by the license terms (which I think you have) this is completely fine. I would have preferred it if you had forked the repo rather than create a copy from scratch; but that's entirely up to you!
